name: CD workflow

on:
    workflow_run:
        workflows: [ "CI workflow" ]
        types: [ completed ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Execute remote ssh
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PASSWORD }}
                  script: |
                      git clone https://github.com/raxj06/github-actions-demo.git
                      cd ~/github-actions-demo
                      git pull origin main
                      docker compose pull
                      docker compose up -d
